export const ALL_PRODUCTS = [
  {
    name: 'Mobile Game',
    products: [
      {
        id: 71,
        title: 'Mobile Legends',
        subTitle: 'Moonton',
        slug: 'mobile-legends',
        description:
          '<p style="text-align:center;" size="0" _root="undefined" __ownerid="undefined" __hash="undefined" __altered="false"><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 24 Jam</span></span></sup></p>',
        code: 'MOBILE_LEGENDS',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/ml gsi-min-fc68.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'https://api-bisnis.vocagame.com/media/ml-helper-saved.png',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
        items: [
          {
            id: 680,
            name: '14 Diamonds (13 + 1 Bonus)',
            price: 3632,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/1-min100-8760.png',
          },
          {
            id: 681,
            name: '42 Diamonds (38 + 4 Bonus)',
            price: 11_231,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/1-min100-8760.png',
          },
          {
            id: 682,
            name: '70 Diamonds (64 + 6 Bonus)',
            price: 18_707,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/1-min100-8760.png',
          },
          {
            id: 683,
            name: '86 Diamonds (78 + 8 Bonus)',
            price: 19_712,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/1-min100-8760.png',
          },
          {
            id: 684,
            name: '140 Diamonds (127 + 13 Bonus)',
            price: 37_449,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/2-min-011f.png',
          },
          {
            id: 685,
            name: '172 Diamonds (156 + 16 Bonus)',
            price: 39_116,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/2-min-011f.png',
          },
          {
            id: 686,
            name: '257 Diamonds (234 + 23 Bonus)',
            price: 59_783,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/3-min-3c04.png',
          },
          {
            id: 687,
            name: '284 Diamonds (254 + 30 Bonus)',
            price: 74_864,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/3-min-3c04.png',
          },
          {
            id: 702,
            name: '344 Diamonds (312 + 32 Bonus)',
            price: 78_232,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/3-min-3c04.png',
          },
          {
            id: 688,
            name: '355 Diamonds (317 + 38 Bonus)',
            price: 93_572,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/3-min-3c04.png',
          },
          {
            id: 689,
            name: '429 Diamonds (383 + 46 Bonus)',
            price: 97_944,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/3-min-3c04.png',
          },
          {
            id: 703,
            name: '514 Diamonds (468 + 46Bonus)',
            price: 117_656,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/4-min1000-eb8c.png',
          },
          {
            id: 692,
            name: '706 Diamonds (625 + 81 Bonus)',
            price: 157_080,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/4-min1000-eb8c.png',
          },
          {
            id: 693,
            name: '716 Diamonds (633 + 83 Bonus)',
            price: 186_473,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/4-min1000-eb8c.png',
          },
          {
            id: 705,
            name: '878 Diamonds (781 + 97 Bonus)',
            price: 196_196,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/4-min1000-eb8c.png',
          },
          {
            id: 706,
            name: '963 Diamonds (859 + 104 Bonus)',
            price: 215_908,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/4-min1000-eb8c.png',
          },
          {
            id: 707,
            name: '1412 Diamonds (1250 + 162 Bonus)',
            price: 314_160,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/5-min2000-43b3.png',
          },
          {
            id: 695,
            name: '1446 Diamonds (1252 + 194 Bonus)',
            price: 374_354,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/5-min2000-43b3.png',
          },
          {
            id: 696,
            name: '2195 Diamonds (1860 + 335 Bonus)',
            price: 471_856,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/5-min2000-43b3.png',
          },
          {
            id: 708,
            name: '2901 Diamonds (2485 + 416 Bonus)',
            price: 628_936,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/5-min2000-43b3.png',
          },
          {
            id: 697,
            name: '2976 Diamonds (2501 + 475 Bonus)',
            price: 742_049,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/5-min2000-43b3.png',
          },
          {
            id: 698,
            name: '3688 Diamonds (3099 + 589 Bonus)',
            price: 787_248,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/6-min-dfda.png',
          },
          {
            id: 709,
            name: '4390 Diamonds (3720 + 670 Bonus)',
            price: 943_712,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/6-min-dfda.png',
          },
          {
            id: 699,
            name: '5532 Diamonds (4649 + 883 Bonus)',
            price: 1_181_488,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/6-min-dfda.png',
          },
          {
            id: 710,
            name: '6238 Diamonds (5274 + 964 Bonus)',
            price: 1_338_568,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/6-min-dfda.png',
          },
          {
            id: 700,
            name: '7502 Diamonds (6252 + 1250 Bonus)',
            price: 1_855_141,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/7-min-f1108.png',
          },
          {
            id: 701,
            name: '9288 Diamonds (7740 + 1548 Bonus)',
            price: 1_965_040,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/7-min-f1108.png',
          },
          {
            id: 691,
            name: 'Twilight Pass',
            price: 130_592,
            priceDiscount: null,
            iconUrl: 'https://api.gamestoreindonesia.com/media/tp-min-56ce.png',
          },
        ],
      },
      {
        id: 57,
        title: 'Mobile Legends Hemat',
        subTitle: 'Moonton',
        slug: 'mobile-legends-hemat',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Semifast Proses 10-180 Menit</span></span></sup><br/><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 09.00 - 21.00 WIB</span></span></sup></p><p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Apabila Melewati Jam Aktif, Maka Akan Di Proses Di Hari Berikutnya !</span></span></sup></p><p></p><p><span style="color:#ff0000"><span style="font-size:14px"><strong>Note</strong><span style="letter-spacing:0.84px">: </span></span></span><strong><span style="color:#ff0000"><span style="font-size:14px">Disarankan order paket fast </span></span><em><u><span style="color:#07a9fe"><a href="https://gamestoreindonesia.com/mobile-legends" target="_blank">Klik Disini</a></span></u></em><span style="color:#ff0000"><span style="font-size:14px"> jika ada event mlbb atau pesanan akan delay ( kalau mau nunggu gapapa </span></span></strong>😉 <span style="color:#ff0000"><span style="font-size:14px"><strong><span style="background-color:#ffffff">)</span></strong></span></span></p>',
        code: 'MOBILE_LEGENDS',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/ml gsi-min-fc68.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'https://api.gamestoreindonesia.com/media/ml-helper-saved.png',
        isFeatured: false,
        siteTitle: 'Mobile Legends Hemat',
        siteDescription:
          'Top up ML Diamond hanya dalam hitungan detik! Cukup masukan Username MLBB Anda, pilih jumlah Diamond yang Anda inginkan, selesaikan pembayaran, dan Diamond akan secara langsung ditambahkan ke akun Mobile Legends Anda.',
        siteMeta: [],
        siteBannerUrl: 'https://api.gamestoreindonesia.com/media/ml gsi-min-fc68.jpg',
      },
      {
        id: 60,
        title: 'Mobile Legends: Gift Skin Item',
        subTitle: 'Moonton',
        slug: 'mobile-legends:-gift-skin-item',
        description:
          '<p style="text-align:center;" size="0" _root="undefined" __ownerid="undefined" __hash="undefined" __altered="false"><strong><sup>RULES:</sup></strong></p><p><sup>1. Follow semua akun Gift Mobile Legends Gamestore Indonesia</sup></p><ul><li>ggsi@01 (1234060856)</li><li>ggsi@02 (1235048791)</li><li>ggsi@03 (1235110009)</li><li>ggsi@04 (1235351930)</li></ul><p><sup>2. Hanya skin shop, sesuaikan nama skin dengan jumlah diamond di skin shop. Tidak bisa skin limited</sup></p><p><sup>3. Lengkapin data yang dibutuhkan</sup></p><p><sup>4. Pilih nominal sesuai dengan jumlah diamond di skin shop</sup></p><p><sup>5. Dalam 1x24 jam Admin akan followback akun kalian (dari salah satu akun diatas). Jika dalam 2x24 jam tidak followback oleh Admin, maka segera kontak Admin GSI</sup></p><p><sup>6. Apabila Customer tidak memfollow akun gift dari GSI selama 1x24 jam, maka proses gift akan dibatalkan dan uang akan hangus.</sup></p><p><sup>7. Estimasi gift 7-14 hari, mohon bersabar ini ujian dan jangan spam Admin</sup></p><p><sup>8. Dilarang Change Name saat delay pertemanan</sup></p><p><sup>9. Untuk gift charisma langsung dikirim dalam waktu 1-6 jam dan tidak perlu follow akun gift</sup></p><p><sup>10. Untuk gift charisma / starlight silahkan isi nama hero &amp; skin sesuai item yang dibeli</sup></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/gsi gift-min-d44e.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'https://api.gamestoreindonesia.com/media/gsi help-min-1322.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 13,
        title: 'PROMO Free Fire',
        subTitle: 'Garena',
        slug: 'promo-free-fire',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 24 Jam</span></span></sup></p>',
        code: 'FREEFIRE',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/ezgif-5922.gif',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'http://api.gamestoreindonesia.com/media/ff-min-f79c.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 12,
        title: 'Free Fire',
        subTitle: 'Garena',
        slug: 'free-fire',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 24 Jam</span></span></sup></p>',
        code: 'FREEFIRE',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/ff-gsi-102b1.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'http://api.gamestoreindonesia.com/media/ff-min-f79c.jpg',
        isFeatured: false,
        siteTitle: 'Free Fire Murah',
        siteDescription:
          'Beli Diamond Free Fire hanya dalam hitungan detik! Cukup masukkan Player ID Free Fire Kamu, pilih jumlah Diamond yang Kamu inginkan, selesaikan pembayaran, dan Diamond tersebut akan langsung masuk ke akun Free Fire Kamu.',
        siteMeta: [],
        siteBannerUrl: 'https://api.gamestoreindonesia.com/media/ff gsi-min-3710f.jpg',
      },
      {
        id: 14,
        title: 'PROMO PUBG Mobile',
        subTitle: 'Tencent',
        slug: 'promo-pubg-mobile',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666"><span style="line-height:1">Proses 1-30 Menit</span></span></span></sup><br/><sup><span style="font-size:12px"><span style="color:#666666"><span style="line-height:1">Layanan Aktif 09.00 - 21.00 WIB</span></span></span></sup></p><p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666"><span style="line-height:1">Apabila Melewati Jam Aktif, Maka Akan Di Proses Di Hari Berikutnya !</span></span></span></sup></p><p></p><p><span style="color:#ff0000"><span style="font-size:14px"><strong>Note</strong><span style="letter-spacing:0.84px">: </span><strong>Khusus server Indonesia.</strong></span></span></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/ezgif-b4a6.gif',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'http://api.gamestoreindonesia.com/media/pubg-min-7907.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 15,
        title: 'PUBG Mobile Indonesia',
        subTitle: 'Tencent',
        slug: 'pubg-mobile-indonesia',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Proses 1-90 Menit</span></span></sup><br/><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 09.00 - 18.45 WIB</span></span></sup></p><p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Apabila Melewati Jam Aktif, Maka Akan Di Proses Di Hari Berikutnya !</span></span></sup></p><p></p><p><span style="color:#ff0000"><span style="font-size:14px"><strong>Note</strong><span style="letter-spacing:0.84px">: </span><strong>Khusus server Indonesia.</strong></span></span></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/pubg gsi-min-9143.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'http://api.gamestoreindonesia.com/media/pubg-min-7907.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 16,
        title: 'PUBG Mobile Global',
        subTitle: 'Tencent',
        slug: 'pubg-mobile-global',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Proses 1-30 Menit</span></span></sup><br/><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 09.00 - 21.00 WIB</span></span></sup></p><p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Apabila Melewati Jam Aktif, Maka Akan Di Proses Di Hari Berikutnya !</span></span></sup></p><p></p><p><span style="color:#ff0000"><span style="font-size:14px"><strong>Note</strong><span style="letter-spacing:0.84px">: </span><strong>Tidak bisa untuk server China / Japanese / Korean / Taiwan / Vietnam.</strong></span></span></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/pubg gsi-min-9143.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'http://api.gamestoreindonesia.com/media/pubg-min-7907.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 18,
        title: 'Sausage Man',
        subTitle: 'XD Global',
        slug: 'sausage-man',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Proses 1-30 Menit</span></span></sup><br/><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 09.00 - 21.00 WIB</span></span></sup></p><p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Apabila Melewati Jam Aktif, Maka Akan Di Proses Di Hari Berikutnya !</span></span></sup></p>',
        code: 'SAUSAGE_MAN',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/sausage gsi-min-e389.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'http://api.gamestoreindonesia.com/media/sman-min-a0f7.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 58,
        title: 'Genshin Impact',
        subTitle: 'HoYoverse',
        slug: 'genshin-impact',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">1-30 Menit</span></span></sup><br/><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 09.00 - 19.00 WIB</span></span></sup></p><p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Apabila Melewati Jam Aktif, Maka Akan Di Proses Di Hari Berikutnya !</span></span></sup></p>',
        code: 'GENSHIN_IMPACT',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/gi-min-6c42.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'https://api.gamestoreindonesia.com/media/genshin-min-d199.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 19,
        title: 'Call of Duty Mobile',
        subTitle: 'Garena',
        slug: 'call-of-duty-mobile',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">1-30 Menit</span></span></sup><br/><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 09.00 - 21.00 WIB</span></span></sup></p><p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Apabila Melewati Jam Aktif, Maka Akan Di Proses Di Hari Berikutnya !</span></span></sup></p><p><span style="color:#ff0000"><span style="font-size:14px"><strong>Note</strong><span style="letter-spacing:0.84px">: </span><strong>Khusus server Indonesia.</strong></span></span></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/codm gsi-min-ec5a.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'http://api.gamestoreindonesia.com/media/codm-min-d9bd.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 50,
        title: 'Apex Legends Mobile',
        subTitle: 'Electronic Arts',
        slug: 'apex-legends-mobile',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Proses 1-30 Menit</span></span></sup><br/><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 09.00 - 21.00 WIB</span></span></sup></p><p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Apabila Melewati Jam Aktif, Maka Akan Di Proses Di Hari Berikutnya !</span></span></sup></p><p><span style="color:#ff0000"><span style="font-size:14px"><strong>Note</strong><span style="letter-spacing:0.84px">: </span><strong>Khusus server Indonesia.</strong></span></span></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/apex gsi-min-102d2.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'https://api.gamestoreindonesia.com/media/apex gsi-min-547f.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 22,
        title: 'Arena of Valor',
        subTitle: 'Garena',
        slug: 'arena-of-valor',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 24 Jam</span></span></sup></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/aov gsi-min-6332.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'http://api.gamestoreindonesia.com/media/aov-min-8de5.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 21,
        title: 'League of Legends: Wild Rift',
        subTitle: 'Riot Games',
        slug: 'league-of-legends:-wild-rift',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Proses 1-30 Menit</span></span></sup><br/><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 09.00 - 21.00 WIB</span></span></sup></p><p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Apabila Melewati Jam Aktif, Maka Akan Di Proses Di Hari Berikutnya !</span></span></sup></p><p><span style="color:#ff0000"><span style="font-size:14px"><strong>Note</strong><span style="letter-spacing:0.84px">: </span><strong>Khusus server Indonesia.</strong></span></span></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/lol gsi-min-717f.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'http://api.gamestoreindonesia.com/media/lol-min-85f2.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 25,
        title: 'Zepeto',
        subTitle: 'Never Z Corp.',
        slug: 'zepeto',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Proses 1-30 Menit</span></span></sup><br/><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 09.00 - 21.00 WIB</span></span></sup></p><p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Apabila Melewati Jam Aktif, Maka Akan Di Proses Di Hari Berikutnya !</span></span></sup></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/zepeto gsi-min-32b3.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'http://api.gamestoreindonesia.com/media/zep-min-96310.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 24,
        title: 'Ragnarok X: Next Generation',
        subTitle: 'Pipo (HK) Limited',
        slug: 'ragnarok-x:-next-generation',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Proses 1-30 Menit</span></span></sup><br/><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 09.00 - 21.00 WIB</span></span></sup></p><p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Apabila Melewati Jam Aktif, Maka Akan Di Proses Di Hari Berikutnya !</span></span></sup></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/rox gsi-min-641f.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'http://api.gamestoreindonesia.com/media/rox-min-e921.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 48,
        title: 'Ragnarok M: Eternal Love',
        subTitle: 'Gravity',
        slug: 'ragnarok-m:-eternal-love',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 24 Jam</span></span></sup></p>',
        code: 'GRAVITY_RAGNAROK_M',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/rom gsi-min-f925.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'https://api.gamestoreindonesia.com/media/rom help-min-41e4.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 27,
        title: 'Honkai Impact 3 Mobile',
        subTitle: 'HoYoverse',
        slug: 'honkai-impact-3-mobile',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">1-30 Menit</span></span></sup><br/><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 09.00 - 21.00 WIB</span></span></sup></p><p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Apabila Melewati Jam Aktif, Maka Akan Di Proses Di Hari Berikutnya !</span></span></sup></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/honkai gsi-min-fcc2.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'http://api.gamestoreindonesia.com/media/hi3-min-56110.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 26,
        title: 'Lords Mobile',
        subTitle: 'IGG',
        slug: 'lords-mobile',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Proses 1-30 Menit</span></span></sup><br/><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 09.00 - 21.00 WIB</span></span></sup></p><p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Apabila Melewati Jam Aktif, Maka Akan Di Proses Di Hari Berikutnya !</span></span></sup></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/lords mobile gsi-min-3729.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'http://api.gamestoreindonesia.com/media/lordsm-min-dec8.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 23,
        title: 'Lokapala',
        subTitle: 'PT Melon Indonesia',
        slug: 'lokapala',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 24 Jam</span></span></sup></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/lokapala gsi-min-7881.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'http://api.gamestoreindonesia.com/media/lp-min-4219.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 20,
        title: 'Hyper Front',
        subTitle: 'NetEase',
        slug: 'hyper-front',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 24 Jam</span></span></sup></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/hyperfront gsi-min-c4ba.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'http://api.gamestoreindonesia.com/media/hp-min-a73d.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 41,
        title: 'Chimeraland',
        subTitle: 'Tencent',
        slug: 'chimeraland',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Proses 1-30 Menit</span></span></sup><br/><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 09.00 - 21.00 WIB</span></span></sup></p><p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Apabila Melewati Jam Aktif, Maka Akan Di Proses Di Hari Berikutnya !</span></span></sup></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/chimeraland gsi-min-4d7d.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'http://api.gamestoreindonesia.com/media/chimeraland-min-adf4.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 29,
        title: 'Dragon Raja',
        subTitle: 'Zloong',
        slug: 'dragon-raja',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 24 Jam</span></span></sup></p>',
        code: 'ZULONG_DRAGON_RAJA',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/dragonraja gsi-min-2c96.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'http://api.gamestoreindonesia.com/media/dragonraja-min-6f36.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 49,
        title: 'Speed Drifters',
        subTitle: 'Garena',
        slug: 'speed-drifters',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 24 Jam</span></span></sup></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/speed drifter gsi-min-9391.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'https://api.gamestoreindonesia.com/media/speeddrifter helper gsi-min-925e.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 30,
        title: 'Life After',
        subTitle: 'NetEase',
        slug: 'life-after',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif  24 Jam</span></span></sup></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/lifeafter gsi-min-9424.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'http://api.gamestoreindonesia.com/media/lifeafter-48c8.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 52,
        title: 'MARVEL Super War',
        subTitle: 'NetEase',
        slug: 'marvel-super-war',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 24 Jam</span></span></sup></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/marvel war-min-78ba.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'https://api.gamestoreindonesia.com/media/help marvel super-min-7654.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 56,
        title: 'Heroes Evolved',
        subTitle: 'Netdragon Websoft',
        slug: 'heroes-evolved',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 24 Jam</span></span></sup></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/heroes evolve gsi-min-4caa.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'https://api.gamestoreindonesia.com/media/heroes evolve help gsi-min-1018e.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 68,
        title: 'Onmyoji Arena',
        subTitle: 'NetEase',
        slug: 'onmyoji-arena',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 09.00 - 21.00 WIB</span></span></sup></p><p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Apabila Melewati Jam Aktif, Maka Akan Di Proses Di Hari Berikutnya !</span></span></sup></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/onmyoji-min-48eb.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'https://api.gamestoreindonesia.com/media/onmyoji help-27eb.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 53,
        title: 'Omega Legends',
        subTitle: 'IGG',
        slug: 'omega-legends',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 24 Jam</span></span></sup></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/omega legends gsi-min-5359.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'https://api.gamestoreindonesia.com/media/help omega legends gsi-min-00c6.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 54,
        title: 'Cloud Song: Saga of Skywalkers',
        subTitle: 'VNG Singapore',
        slug: 'cloud-song:-saga-of-skywalkers',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 24 Jam</span></span></sup></p>',
        code: 'VNG_CLOUD_SONG',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/cloudsong gsi-min-608a.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'https://api.gamestoreindonesia.com/media/cloudsong help gsi-min-d6d2.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 55,
        title: 'Laplace M',
        subTitle: 'Zlong',
        slug: 'laplace-m',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 24 Jam</span></span></sup></p>',
        code: 'ZLONGAME',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/laplace gsi-min-275e.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'https://api.gamestoreindonesia.com/media/laplace help-min-c2ae.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 59,
        title: 'Super SUS',
        subTitle: 'PI Productions',
        slug: 'super-sus',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Proses 1-30 Menit</span></span></sup><br/><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 09.00 - 21.00 WIB</span></span></sup></p><p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Apabila Melewati Jam Aktif, Maka Akan Di Proses Di Hari Berikutnya !</span></span></sup></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/super sus gsi-min-257c.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'https://api.gamestoreindonesia.com/media/supersus help gsi-min-2955.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 61,
        title: 'One Punch Man: The Strongest',
        subTitle: 'FingerFun',
        slug: 'one-punch-man-:-the-strongest',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 24 Jam</span></span></sup></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/opm gsi-min-e674.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'https://api.gamestoreindonesia.com/media/help opm-min-a35e.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 62,
        title: 'MU Origin 2',
        subTitle: 'Gamenow Technology',
        slug: 'mu-origin-2',
        description:
          '<p style="text-align:center;"><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 24 Jam</span></span></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/muorigin 2 gsi-min-728a.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'https://api.gamestoreindonesia.com/media/mu origins 2 help-min-f8d9.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 70,
        title: 'Never After',
        subTitle: 'NetEase',
        slug: 'never-after',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 09.00 - 21.00 WIB</span></span></sup></p><p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Apabila Melewati Jam Aktif, Maka Akan Di Proses Di Hari Berikutnya !</span></span></sup></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/neverafter copy-min-c434.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'https://api.gamestoreindonesia.com/media/neverafter help-min-101fc.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 63,
        title: 'Crossing Void - Global',
        subTitle: '91 Act',
        slug: 'crossing-void-global',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 24 Jam</span></span></sup></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/crossing void gsi-min-f2e6.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'https://api.gamestoreindonesia.com/media/help crossing void gsi-min-2d410.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 65,
        title: 'Love Nikki',
        subTitle: 'ELEX',
        slug: 'love-nikkiz',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 24 Jam</span></span></sup></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/love nikki gsi-min-1547.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'https://api.gamestoreindonesia.com/media/help love nikki gsi-min-fa23.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
    ],
  },
  {
    name: 'PC Game',
    products: [
      {
        id: 31,
        title: 'Valorant',
        subTitle: 'Riot Games',
        slug: 'valorant',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Proses 1-30 Menit</span></span></sup><br/><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 09.00 - 21.00 WIB</span></span></sup></p><p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Apabila Melewati Jam Aktif, Maka Akan Di Proses Di Hari Berikutnya !</span></span></sup></p><p><span style="color:#ff0000"><span style="font-size:14px"><strong>Note</strong><span style="letter-spacing:0.84px">: </span><strong>Khusus server Indonesia.</strong></span></span></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/valorant gsi-min-6d1b.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'http://api.gamestoreindonesia.com/media/val-min-5ce10.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 32,
        title: 'Point Blank',
        subTitle: 'Zepetto',
        slug: 'point-blank',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 24 Jam</span></span></sup></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/pb gsi-min-e1fa.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'http://api.gamestoreindonesia.com/media/pb-min-dc93.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
    ],
  },
  {
    name: 'Others',
    products: [
      {
        id: 33,
        title: 'TELKOMSEL',
        subTitle: 'Telkom Indonesia',
        slug: 'telkomsel',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Proses 1-30 Menit</span></span></sup><br/><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 09.00 - 21.00 WIB</span></span></sup></p><p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Apabila Melewati Jam Aktif, Maka Akan Di Proses Di Hari Berikutnya !</span></span></sup></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/tsel gsi-min-506a.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 34,
        title: 'XL / AXIS',
        subTitle: 'XL Axiata',
        slug: 'xl-axis',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Proses 1-30 Menit</span></span></sup><br/><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 09.00 - 21.00 WIB</span></span></sup></p><p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Apabila Melewati Jam Aktif, Maka Akan Di Proses Di Hari Berikutnya !</span></span></sup></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/xl axis gsi-min-35a8.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
      {
        id: 35,
        title: 'TOKEN LISTRIK',
        subTitle: 'PLN',
        slug: 'token-listrik',
        description:
          '<p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Proses 1-30 Menit</span></span></sup><br/><sup><span style="font-size:12px"><span style="color:#666666">Layanan Aktif 09.00 - 21.00 WIB</span></span></sup></p><p style="text-align:center;"><sup><span style="font-size:12px"><span style="color:#666666">Apabila Melewati Jam Aktif, Maka Akan Di Proses Di Hari Berikutnya !</span></span></sup></p>',
        code: 'NOVERIFY',
        type: 'topup',
        logoUrl: 'https://api.gamestoreindonesia.com/media/pln gsi-min-7c56.jpg',
        bannerUrl: 'https://api.gamestoreindonesia.com/media/info-min-c4ee.jpg',
        helperUrl: 'http://api.gamestoreindonesia.com/media/pln-min-5d7c.jpg',
        isFeatured: false,
        siteTitle: null,
        siteDescription: null,
        siteMeta: [],
        siteBannerUrl: null,
      },
    ],
  },
];
