export const PAYMENT_CHANNELS_GROUP = [
  {
    group: 'Bank Transfer',
    datas: [
      {
        id: 53,
        name: 'Bank BCA',
        accountName: 'YUDHI AMRULLAH',
        accountNumber: '7870733555',
        group: 'banktransfer',
        code: 'bca',
        feeFlat: 0,
        minAmount: 10_000,
        maxAmount: 0,
        feePercent: '0',
        iconUrl: 'https://api.gamestoreindonesia.com/media/bca-5e57.png',
        description:
          '<p><strong><span style="color:#ff0000"><span style="font-size:16px">Dilarang memberikan tambahan / membulatkan nominal / tips !</span></span></strong> Mohon transfer sesuai <strong><span style="color:#ff0000"><span style="font-size:16px">total pembayaran</span></span></strong> dengan benar atau payment anda akan hangus dan tidak di kembalikan !</p>',
        paymentMethods: null,
        instruction: null,
        isActive: true,
        isOnline: false,
      },
    ],
  },
  {
    group: 'QRIS',
    datas: [
      {
        id: 25,
        name: 'QRIS 2',
        accountName: null,
        accountNumber: null,
        group: 'qris',
        code: 'QRISC',
        feeFlat: 800,
        minAmount: null,
        maxAmount: 0,
        feePercent: '2',
        iconUrl: 'https://api.gamestoreindonesia.com/media/z-min-0f26.png',
        description: '<p></p>',
        paymentMethods: null,
        instruction: {},
        isActive: true,
        isOnline: true,
      },
      {
        id: 45,
        name: 'QRIS',
        accountName: null,
        accountNumber: null,
        group: 'qris',
        code: 'QRIS',
        feeFlat: 0,
        minAmount: null,
        maxAmount: 0,
        feePercent: '2',
        iconUrl: 'https://api.gamestoreindonesia.com/media/qris gsi-min-5c51.png',
        description: '<p></p>',
        paymentMethods: null,
        instruction: null,
        isActive: true,
        isOnline: true,
      },
    ],
  },
  {
    group: 'E - Wallet',
    datas: [
      {
        id: 44,
        name: 'ShoopePay',
        accountName: null,
        accountNumber: null,
        group: 'ewallet',
        code: 'ID_SHOPEEPAY',
        feeFlat: 0,
        minAmount: null,
        maxAmount: 0,
        feePercent: '4.5',
        iconUrl: 'https://api.gamestoreindonesia.com/media/gsi shopee-81028.png',
        description: '<p></p>',
        paymentMethods: null,
        instruction: null,
        isActive: true,
        isOnline: true,
      },
      {
        id: 43,
        name: 'LinkAja',
        accountName: null,
        accountNumber: null,
        group: 'ewallet',
        code: 'ID_LINKAJA',
        feeFlat: 0,
        minAmount: null,
        maxAmount: 0,
        feePercent: '3',
        iconUrl: 'http://api.gamestoreindonesia.com/media/linkaja-min-3919.png',
        description: '<p></p>',
        paymentMethods: null,
        instruction: null,
        isActive: true,
        isOnline: true,
      },
      {
        id: 42,
        name: 'DANA',
        accountName: null,
        accountNumber: null,
        group: 'ewallet',
        code: 'ID_DANA',
        feeFlat: 0,
        minAmount: null,
        maxAmount: 0,
        feePercent: '3',
        iconUrl: 'http://api.gamestoreindonesia.com/media/dana-418f.png',
        description: '<p></p>',
        paymentMethods: null,
        instruction: null,
        isActive: true,
        isOnline: true,
      },
      {
        id: 41,
        name: 'OVO',
        accountName: null,
        accountNumber: null,
        group: 'ewallet',
        code: 'ID_OVO',
        feeFlat: 0,
        minAmount: null,
        maxAmount: 0,
        feePercent: '4.5',
        iconUrl: 'http://api.gamestoreindonesia.com/media/ovo-6d34.png',
        description: '<p></p>',
        paymentMethods: null,
        instruction: null,
        isActive: true,
        isOnline: true,
      },
    ],
  },
  {
    group: 'Virtual Account',
    datas: [
      {
        id: 13,
        name: 'Permata Virtual Account',
        accountName: null,
        accountNumber: null,
        group: 'va',
        code: 'PERMATAVA',
        feeFlat: 4250,
        minAmount: null,
        maxAmount: 0,
        feePercent: '0',
        iconUrl: 'http://api.gamestoreindonesia.com/media/permata-94d10.png',
        description: '<p></p>',
        paymentMethods: null,
        instruction: null,
        isActive: true,
        isOnline: true,
      },
      {
        id: 19,
        name: 'CIMB Virtual Account',
        accountName: null,
        accountNumber: null,
        group: 'va',
        code: 'CIMBVA',
        feeFlat: 4250,
        minAmount: null,
        maxAmount: 0,
        feePercent: '0',
        iconUrl: 'http://api.gamestoreindonesia.com/media/cimb-5e210.png',
        description: '<p></p>',
        paymentMethods: null,
        instruction: null,
        isActive: true,
        isOnline: true,
      },
      {
        id: 18,
        name: 'Muamalat Virtual Account',
        accountName: null,
        accountNumber: null,
        group: 'va',
        code: 'MUAMALATVA',
        feeFlat: 4250,
        minAmount: null,
        maxAmount: 0,
        feePercent: '0',
        iconUrl: 'http://api.gamestoreindonesia.com/media/muamalat-3711.png',
        description: '<p></p>',
        paymentMethods: null,
        instruction: null,
        isActive: true,
        isOnline: true,
      },
      {
        id: 17,
        name: 'Sinarmas Virtual Account',
        accountName: null,
        accountNumber: null,
        group: 'va',
        code: 'SMSVA',
        feeFlat: 4250,
        minAmount: null,
        maxAmount: 0,
        feePercent: '0',
        iconUrl: 'http://api.gamestoreindonesia.com/media/sinarmas-c108b.png',
        description: '<p></p>',
        paymentMethods: null,
        instruction: null,
        isActive: true,
        isOnline: true,
      },
      {
        id: 12,
        name: 'Maybank Virtual Account',
        accountName: null,
        accountNumber: null,
        group: 'va',
        code: 'MYBVA',
        feeFlat: 4250,
        minAmount: null,
        maxAmount: 0,
        feePercent: '0',
        iconUrl: 'http://api.gamestoreindonesia.com/media/maybank-3043.png',
        description: '<p></p>',
        paymentMethods: null,
        instruction: null,
        isActive: true,
        isOnline: true,
      },
      {
        id: 30,
        name: 'BRI Virtual Account',
        accountName: null,
        accountNumber: null,
        group: 'va',
        code: 'BRI',
        feeFlat: 5000,
        minAmount: null,
        maxAmount: 0,
        feePercent: '0',
        iconUrl: 'http://api.gamestoreindonesia.com/media/bri-0dd9.png',
        description: '<p></p>',
        paymentMethods: null,
        instruction: null,
        isActive: true,
        isOnline: true,
      },
      {
        id: 31,
        name: 'BNI Virtual Account',
        accountName: null,
        accountNumber: null,
        group: 'va',
        code: 'BNI',
        feeFlat: 5000,
        minAmount: null,
        maxAmount: 0,
        feePercent: '0',
        iconUrl: 'http://api.gamestoreindonesia.com/media/bni-102fa.png',
        description: '<p></p>',
        paymentMethods: null,
        instruction: null,
        isActive: true,
        isOnline: true,
      },
      {
        id: 32,
        name: 'Mandiri Virtual Account',
        accountName: null,
        accountNumber: null,
        group: 'va',
        code: 'MANDIRI',
        feeFlat: 5000,
        minAmount: null,
        maxAmount: 0,
        feePercent: '0',
        iconUrl: 'http://api.gamestoreindonesia.com/media/mandiri-410a10.png',
        description: '<p></p>',
        paymentMethods: [
          {
            title: "Pembayaran via Mandiri Livin' Biru",
            content:
              '• Login ke mobile banking Anda\n• Pilih menu Pembayaran lalu klik menu Multipayment\n• Pilih Penyedia Jasa: Xendit (88908)\n• Masukkan Nomor VA\n• Masukkan Nominal\n• Detail transaksi akan ditampilkan, pastikan data sudah sesuai\n• Klik tombol Konfirmasi\n• Transaksi sukses, simpan bukti transaksi Anda',
          },
          {
            title: "Pembayaran via Mandiri Livin' Kuning",
            content:
              '• Login ke mobile banking Anda\n• Pilih menu Bayar lalu klik menu E-Commerce\n• Masukkan Kode Xendit (88908)\n• Masukkan Nomor VA\n• Masukkan Nominal\n• Detail transaksi akan ditampilkan, pastikan data sudah sesuai\n• Klik tombol Konfirmasi\n• Transaksi sukses, simpan bukti transaksi Anda',
          },
          {
            title: 'Pembayaran via ATM Mandiri',
            content:
              '• Masukkan kartu ATM & isi PIN ATM Anda\n• Pilih menu Bayar/Beli lalu pilih menu Lainnya\n• Pilih lagi menu Lainnya\n• Pilih menu Multi Payment\n• Masukkan kode Xendit (88908) lalu tekan Benar\n• Masukkan Nomor VA\n• Tekan 1 lalu tekan YA\n• Transaksi sukses, simpan bukti transaksi Anda',
          },
        ],
        instruction: null,
        isActive: true,
        isOnline: true,
      },
      {
        id: 33,
        name: 'Permata Virtual Account',
        accountName: null,
        accountNumber: null,
        group: 'va',
        code: 'PERMATA',
        feeFlat: 5000,
        minAmount: null,
        maxAmount: 0,
        feePercent: '0',
        iconUrl: 'http://api.gamestoreindonesia.com/media/permata-94d10.png',
        description: '<p></p>',
        paymentMethods: null,
        instruction: null,
        isActive: true,
        isOnline: true,
      },
      {
        id: 34,
        name: 'Sahabat Sampoerna Virtual Account',
        accountName: null,
        accountNumber: null,
        group: 'va',
        code: 'SAHABAT_SAMPOERNA',
        feeFlat: 5000,
        minAmount: null,
        maxAmount: 0,
        feePercent: '0',
        iconUrl: 'http://api.gamestoreindonesia.com/media/sampoerna-c2f1.png',
        description: '<p></p>',
        paymentMethods: null,
        instruction: null,
        isActive: true,
        isOnline: true,
      },
      {
        id: 36,
        name: 'BSI Virtual Account',
        accountName: null,
        accountNumber: null,
        group: 'va',
        code: 'BSI',
        feeFlat: 5000,
        minAmount: null,
        maxAmount: 0,
        feePercent: '0',
        iconUrl: 'http://api.gamestoreindonesia.com/media/bsi-min-7108.png',
        description: '<p></p>',
        paymentMethods: null,
        instruction: null,
        isActive: true,
        isOnline: true,
      },
      {
        id: 37,
        name: 'BJB Virtual Account',
        accountName: null,
        accountNumber: null,
        group: 'va',
        code: 'BJB',
        feeFlat: 5000,
        minAmount: null,
        maxAmount: 0,
        feePercent: '0',
        iconUrl: 'http://api.gamestoreindonesia.com/media/bjb-min (1)-1619.png',
        description: '<p></p>',
        paymentMethods: null,
        instruction: null,
        isActive: true,
        isOnline: true,
      },
    ],
  },
  {
    group: 'Convenience Store',
    datas: [
      {
        id: 23,
        name: 'Alfamidi',
        accountName: null,
        accountNumber: null,
        group: 'cstore',
        code: 'ALFAMIDI',
        feeFlat: 6000,
        minAmount: null,
        maxAmount: 0,
        feePercent: '0',
        iconUrl: 'http://api.gamestoreindonesia.com/media/alfamidi-11096.png',
        description: '<p></p>',
        paymentMethods: [
          {
            title: 'Cara melakukan pembayaran gerai Alfamidi',
            content:
              '• Catat kode Virtual Account\n• Bawa kode pembayaran tersebut ke gerai Alfamidi\n• Informasikan kepada kasir pembayaran menggunakan <b>PLASAMALL</b>\n• Berikan kode pembayaran ke kasir\n• Kasir akan memasukkan kode pembayaran\n• Bayar sesuai nominal ditambah Admin Alfamidi\n• Ambil tanda terima pembayaran\n• Selesai',
          },
        ],
        instruction: null,
        isActive: true,
        isOnline: true,
      },
      {
        id: 22,
        name: 'Indomaret',
        accountName: null,
        accountNumber: null,
        group: 'cstore',
        code: 'INDOMARET',
        feeFlat: 3500,
        minAmount: null,
        maxAmount: 0,
        feePercent: '0',
        iconUrl: 'http://api.gamestoreindonesia.com/media/indomaret-cf710.png',
        description: '<p></p>',
        paymentMethods: [
          {
            title: 'Cara melakukan pembayaran gerai Indomaret',
            content:
              '• Catat kode Virtual Account\n• Bawa kode pembayaran tersebut ke gerai Indomaret\n• Informasikan kepada kasir pembayaran menggunakan <b>LINKITA</b>\n• Berikan kode pembayaran ke kasir\n• Kasir akan memasukkan kode pembayaran\n• Bayar sesuai nominal ditambah Admin Indomaret\n• Ambil tanda terima pembayaran\n• Selesai',
          },
        ],
        instruction: null,
        isActive: true,
        isOnline: true,
      },
      {
        id: 21,
        name: 'Alfamart 2',
        accountName: null,
        accountNumber: null,
        group: 'cstore',
        code: 'ALFAMART',
        feeFlat: 6000,
        minAmount: 0,
        maxAmount: 0,
        feePercent: '0',
        iconUrl: 'http://api.gamestoreindonesia.com/media/alfamart-101040.png',
        description: '<p></p>',
        paymentMethods: [
          {
            title: 'Cara melakukan pembayaran gerai Alfamart',
            content:
              '• Catat kode Virtual Account\n• Bawa kode pembayaran tersebut ke gerai Alfamart\n• Informasikan kepada kasir pembayaran menggunakan <b>PLASAMALL</b>\n• Berikan kode pembayaran ke kasir\n• Kasir akan memasukkan kode pembayaran\n• Bayar sesuai nominal ditambah Admin Alfamart\n• Ambil tanda terima pembayaran\n• Selesai',
          },
        ],
        instruction: {
          title: 'Intruksi Pembayaran',
          contents: [
            {
              title: 'Alfamart',
              steps: [
                'Catat dan simpan kode pembayaran Alfamart Anda, misal: 32133707xxxx1594',
                'Datangi kasir Alfamart terdekat dan beritahukan pada kasir bahwa Anda ingin melakukan pembayaran "PLASAMALL"',
                'Beritahukan kode pembayaran Alfamart Anda pada kasir dan silahkan lakukan pembayaran Anda senilai',
                'Simpan struk pembayaran Anda sebagai tanda bukti pembayaran yang sah',
              ],
            },
          ],
        },
        isActive: true,
        isOnline: true,
      },
    ],
  },
];
